apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.6
        args: ["start"]
        env:
        - name: KC_HOSTNAME
          value: "localhost"
        - name: KC_HTTP_PORT
          value: "5010"
        - name: KC_HTTPS_PORT
          value: "5011"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "password"
        ports:
        - containerPort: 5010
        - containerPort: 5011
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 5010
    targetPort: 5010
  - name: https
    port: 5011
    targetPort: 5011
  type: LoadBalancer 