apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  DB_USER: YXV0aF91c2Vy  # auth_user
  DB_PASSWORD: YXV0aF9wYXNz  # auth_pass
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl  # your_jwt_secret_key_here
  RABBITMQ_USERNAME: cHhzempnZWI=  # pxszjgeb
  RABBITMQ_PASSWORD: Q0FRWGFoRjd4VmFqRjBPYkFuT09tNjhGakVfNTBvSlQ=  # CAQXahF7xVajF0ObAnOOm68FjE_50oJT
  KEYCLOAK_CLIENT_SECRET: UHQ5bGxpcTVQMk5qc0xqQU9US1gzOW5XU3hpNHBTb0o=  # Pt9lliq5P2NjsLjAOTKX39nWSxi4pSoJ
  KEYCLOAK_ADMIN_PASSWORD: cGFzc3dvcmQ=  # password 